### ISSUE TITLE
java.lang.ClassCastException: org.dom4j.io.SAXReader cannot be cast to org.dom4j.io.SAXReader

### ISSUE THREAD

**Issue by yupd** [jvm-rasp/jrasp-agent#29]
java.lang.ClassCastException: org.dom4j.io.SAXReader cannot be cast to org.dom4j.io.SAXReader
		at com.jrasp.agent.module.xxe.hook.XxeModule$6.before(XxeModule.java:77)
		at com.jrasp.agent.api.listener.AdviceAdapterListener.switchEvent(AdviceAdapterListener.java:61)
		at com.jrasp.agent.api.listener.AdviceAdapterListener.onEvent(AdviceAdapterListener.java:32)
		at com.jrasp.agent.core.enhance.weaver.EventListenerHandler.handleEvent(EventListenerHandler.java:87)
		at com.jrasp.agent.core.enhance.weaver.EventListenerHandler.handleOnBefore(EventListenerHandler.java:260)
		at java.com.jrasp.agent.bridge110.Spy.spyMethodOnBefore(Spy.java:101)
		at org.dom4j.io.SAXReader.read(SAXReader.java)
		at org.dom4j.io.SAXReader.read(SAXReader.java:264)
		at com.xxx.root.RootUtil.getTitle(RootUtil.java:27)
		at org.apache.jsp.index_jsp._jspService(index_jsp.java:119)
		at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
		at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:476)
		at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:386)
		at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:330)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)

**Comment by xl1605368195** [comment]
已经修复
https://github.com/jvm-rasp/jrasp-agent/pull/30
