### ISSUE TITLE
[bug] clean ProtectionDomain in acc failed.

### ISSUE THREAD

**Issue by yupd** [jvm-rasp/jrasp-agent#50]
# jdk 版本
```
java -version
java version "1.6.0_21"
Java(TM) SE Runtime Environment (build 1.6.0_21-b06)
Java HotSpot(TM) 64-Bit Server VM (build 17.0-b16, mixed mode)
```

# 调用栈
```
2023-11-01 11:16:10.827 WARNING WIN-3QSDF286MOL [main] [com.jrasp.agent.core.classloader.ModuleJarClassLoader.<init>] clean ProtectionDomain in acc failed.
	com.jrasp.agent.core.util.UnCaughtException: java.lang.NoSuchMethodException: java.security.AccessControlContext.getContext()
	at com.jrasp.agent.core.util.RaspReflectUtils.unCaughtGetClassDeclaredJavaMethod(RaspReflectUtils.java:31)
	at com.jrasp.agent.core.classloader.ModuleJarClassLoader.cleanProtectionDomainWhichCameFromModuleJarClassLoader(ModuleJarClassLoader.java:76)
	at com.jrasp.agent.core.classloader.ModuleJarClassLoader.<init>(ModuleJarClassLoader.java:59)
	at com.jrasp.agent.core.classloader.ModuleJarClassLoader.<init>(ModuleJarClassLoader.java:35)
	at com.jrasp.agent.core.manager.ModuleJarLoader.load(ModuleJarLoader.java:118)
	at com.jrasp.agent.core.manager.ModuleLibLoader.load(ModuleLibLoader.java:46)
	at com.jrasp.agent.core.manager.DefaultCoreModuleManager.reset(DefaultCoreModuleManager.java:509)
	at com.jrasp.agent.core.server.socket.SocketServer.bind(SocketServer.java:78)
	at com.jrasp.agent.core.server.ProxyCoreServer.bind(ProxyCoreServer.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at com.jrasp.agent.launcher110.AgentLauncher.install(AgentLauncher.java:164)
	at com.jrasp.agent.launcher110.AgentLauncher.premain(AgentLauncher.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:323)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:338)
Caused by: java.lang.NoSuchMethodException: java.security.AccessControlContext.getContext()
	at java.lang.Class.getDeclaredMethod(Class.java:1937)
	at com.jrasp.agent.core.util.RaspReflectUtils.unCaughtGetClassDeclaredJavaMethod(RaspReflectUtils.java:29)
	... 20 more
```

**Comment by yupd** [comment]
# 解决方法
```java
private void cleanProtectionDomainWhichCameFromModuleJarClassLoader() {

        // got ProtectionDomain[] from URLClassLoader's acc
        final AccessControlContext acc = unCaughtGetClassDeclaredJavaFieldValue(URLClassLoader.class, "acc", this);
        //final ProtectionDomain[] protectionDomainArray = unCaughtInvokeMethod(
        //        unCaughtGetClassDeclaredJavaMethod(AccessControlContext.class, "getContext"),
        //        acc
        //);

       // 通过反射字段获取值，增加jdk兼容性
       final ProtectionDomain[] protectionDomainArray = unCaughtGetClassDeclaredJavaFieldValue(AccessControlContext.class, "context", acc);

    }
```

**Comment by xl1605368195** [comment]
好的，我这边加到master上。

**Comment by xl1605368195** [comment]
https://github.com/jvm-rasp/jrasp-agent/commit/9708480f2f534660d67133a15fc53a4279e393f3
